export const csvData_20250319223134 = `"[Client] Client","[Client] Business Structure","[Client] Business Number","[Client] Account Manager","[Client] Tax Agent","[Client] Group(s)"
"ABRAHAM LLP","Partnership","65 101 795 397","Nikunj Simariya","",""
"Abraham Venture Trust","Trust","64 101 586 230","Dilnar Tangri","Manish Sheladiya",""
"Amazing Family Trust","Trust","84 118 155 258","","Nikunj Simariya","Nation Super"
"Amazing Grace accupuncture clinic","Sole Trader","75 725 627 667","Divy M","",""
"Amazing Pet Care Pty Ltd","Company","49 898 197 911","Manish Sheladia","Manish Sheladiya","Amazing Group"
"Andy Smith Remove","","","","Manish Sheladiya","AB SMITH GROUP"
"ARNAUD ABRAHAM ","Individual","19 114 194 310","Sachin Bhatnagar","Nikunj Simariya",""
"Atlas Corp. Pty Ltd","Company","11 688 022 083","","",""
"Aussie Trading Trust","Trust","37 849 875 881","Manish Sheladia","",""
"Balmoral Pastoral Concepts Pty Ltd","Company","13 447 453 166","Jocelyn Vere","Nikunj Simariya","Nation Super"
"BDP Group Ltd","Company","13 860 671 162","","",""
"Billion $ Unicorn Pty Ltd","Company","47 661 378 838","Manish Sheladia","Manish Sheladiya",""
"Bluebird Beverages Pty Ltd","Company","78 004 551 473","","",""
"Bondi Consulting Partners","Partnership","29 580 551 984","Manish Sheladia","",""
"Bray Family Superannuation Fund","Self Managed Superannuation Fund","63 059 981 823","Manish Sheladia","",""
"Cloudoffis Demo Pty Ltd","Company","23 614 069 859","Divy M","Nikunj Simariya","Cloudoffis"
"CloudOffis DMS Pty Ltd","Company","15 529 825 132","Divy M","","Cloudoffis"
"Cloudoffis Superannuation Fund","Self Managed Superannuation Fund","68 604 480 391","","","Cloudoffis"
"Dan Smith","Individual","","","","Cloudoffis"
"Daniel Pine","Individual","","Manish Sheladia","",""
"Darshit Trivedi","Company","","Dilnar Tangri","",""
"Darshit Trivedi","Company","26 911 245 195","Manish Sheladia","Manish Sheladiya",""
"Del Juice and Company","Partnership","76 750 687 489","Divy M","",""
"Delta Clothing Pty Ltd","Company","80 561 020 084","","",""
"Diana Smith","Individual","","","","Cloudoffis"
"Dino's Family Business Trust","Trust","16 009 360 570","","",""
"Ditto Music Pty Ltd","Company","20 197 780 498","Divy M","Manish Sheladiya",""
"Domicile New Trust","Trust","60 140 918 154","","Nikunj Simariya","Multi Services Group"
"Dr. B. A. Smith","Individual","","Divy M","",""
"Dreamware Infotech Trust","Trust","18 091 426 550","Manish Sheladia","",""
"Dronglass Garden Pty Ltd","Company","77 164 160 446","","Nikunj Simariya","Nation Super"
"Early Bird Retirement Fund","Self Managed Superannuation Fund","60 140 023 892","","Nikunj Simariya","Multi Services Group"
"Eddie Anderson","Sole Trader","65 931 852 953","Divy M","",""
"Elizabeth Andrew","Individual","","","Nikunj Simariya","Nation Super"
"Emma Abbott","Individual","","Manish Sheladia","",""
"Expert Superannuation Fund","Self Managed Superannuation Fund","40 382 360 375","","Manish Sheladiya","Nation Super"
"Forest Sky Partners","Partnership","53 310 725 464","","Manish Sheladiya","Nation Super"
"Glenn Jacobs","Individual","","","",""
"Globus Client","Company","","Manish Sheladia","",""
"Govt club","Government Entity","","","",""
"Harrison Family Super Fund","Self Managed Superannuation Fund","","Nikunj Simariya","Nikunj Simariya","Harrison Group"
"Health Juice Pty Ltd","Company","21 303 071 242","Jocelyn Vere","",""
"Hero Honda","Company","","","",""
"Horizon Company","Company","","","",""
"Hunter Valley Trust","Trust","","","",""
"Incore Trust","Trust","","Divy M","",""
"Info Trust","Company","","Manish Sheladia","",""
"Infynitec","Sole Trader","","Divy M","",""
"I-Square Trader","Sole Trader","","Nikunj 1","",""
"Jack Harrison","Individual","","Nikunj Simariya","","Harrison Group"
"JOICE ABRAHAM","Individual","89 458 109 748","Nikunj Simariya","Manish Sheladiya",""
"Jplan ","Individual","","","",""
"Julie Soul","Individual","","","",""
"KESHA ABRAHAM ","Individual","15 530 812 246","Krupa 1902 Patel 1902","",""
"Kim Harrison","Individual","","Nikunj Simariya","Nikunj Simariya","Harrison Group"
"Kreya Trader","Sole Trader","","Manish Sheladia","",""
"Kumars ","Sole Trader","","Nikunj 1","",""
"Lavender Lane Florist","Company","","","",""
"Lily Andrew","Individual","","","Manish Sheladiya","Nation Super"
"Liz Campbell","Individual","","Manish Sheladia","Manish Sheladiya","Amazing Group"
"Logitech","Company","","","",""
"Logitech Pvt Ltd ","Company","","","",""
"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s","Company","","","",""
"Lotus-Pink Capita","Individual","","Manish Sheladia","",""
"M.D Modi","Trust","","Manish Sheladia","",""
"M.N.Trust ","Trust","99 495 452 829","Manish Sheladia","",""
"M/S Axil","Company","","","",""
"M/s Ceacon","Sole Trader","","Nikunj Simariya","",""
"M/s. Avestaa","Company","","prashant shah","",""
"M/s. Deltacore","Sole Trader","","Nikunj 1","",""
"M/s. Skube","Sole Trader","","Nikunj 1","",""
"Magazine Networks","Individual","","Divy M","",""
"Manish smith","Sole Trader","","Nikunj 1","",""
"Marvel Cloud","Marvel ","","","",""
"Marvel Test","TEST ","","","",""
"Melbourne Pvt Ltd.","Individual","","Manish Sheladia","",""
"Merak Global","Company","","Manish Sheladia","",""
"MK Multivision","Company","","Nikunj 1","",""
"MM Traders ","Sole Trader","","Manish Sheladia","",""
"Modi Pvt LTD","Sole Trader","32 895 633 132","Divy M","",""
"Mr A B Smith","Individual","","Manish Sheladia","Manish Sheladiya","AB SMITH GROUP"
"Mr D K Smith","Individual","","Manish Sheladia","Manish Sheladiya","AB SMITH GROUP"
"mr DA smith","Sole Trader","","","",""
"Mr flash","Individual","","prashant shah","",""
"MR R J Smith","Individual","","Manish Sheladia","Manish Sheladiya","AB SMITH GROUP"
"Mr. Joyous","Partnership","","Nikunj 1","",""
"Mr. N. M Shah","Company","","Nikunj Simariya","",""
"Mr. N.P. Shah","Trust","","prashant shah","",""
"Mr.N.N. smith","Individual","","Nikunj 1","",""
"Mrs B A Smith","Individual","","Manish Sheladia","Manish Sheladiya","AB SMITH GROUP"
"Mrs. D.P ","Partnership","","prashant shah","",""
"Mrs. Modi","Company","","Divy M","",""
"MS Trust","Club or Society","","","",""
"MS Trust","Unit Trust","","prashant shah","",""
"Multi Services Pty Ltd","Company","30 814 435 595","","Manish Sheladiya","Multi Services Group"
"NexaMind","Company","","","",""
"NexaWavez","Company","","","",""
"Nikunj ","Individual","","Nikunj 1","",""
"Nikunj Cloudoffis Pty Ltd","Company","","Manish Sheladia","",""
"Nikunj Company","Company","","Nikunj Simariya","",""
"Nikunj Demo File Prep Pty Ltd","Company","23 614 069 859","Manish Sheladia","Manish Sheladiya",""
"Nikunj trader","Sole Trader","","Nikunj 1","",""
"Nikunj Trust","Trust","","Nikunj 1","",""
"Norman Ross Campbell","Individual","","Manish Sheladia","Manish Sheladiya","Amazing Group"
"Northern Lights Ventures","Individual","","","",""
"NovusTech","Company","","","",""
"Null Narayan Niwas Pty Ltd","","","","",""
"NxtGenius","Company","","Divy M","",""
"Opal Coast Pty Ltd","Company","40 925 706 679","Nikunj Simariya","Manish Sheladiya","Harrison Group"
"Opportunity corp Pty Ltd","Company","","Manish Sheladia","",""
"P.N Trader","Sole Trader","","Nikunj 1","",""
"Parakramsinh Parmar","Company","","Divy M","",""
"Perth Partners","Partnership","","Nikunj 1","",""
"Pine Grove Partners","Company","","","",""
"Polar Comapny","Company","","","",""
"Popeye Pty Ltd","Company","","","",""
"Popeyes Pty Ltd","Company","27 695 908 806","Manish Sheladia","Manish Sheladiya",""
"Prashant Trader ","Sole Trader","","prashant shah","",""
"Protonix Ltd","Individual","","Manish Sheladia","",""
"PTU LTD","Company","","","",""
"Racer","Company","","Divy M","Manish Sheladiya",""
"Rainbow Rising Co.","Individual","","","",""
"Ravi Modi","Trust","","Divy M","",""
"Redwood Partners","Company","","","",""
"Rhyme","Individual","","","",""
"Richard Thomson","Individual","","","Nikunj Simariya","Multi Services Group"
"Riverfront Trust","Trust","","","",""
"ROSSY ABRAHAM ","Individual","64 101 586 230","Jocelyn Vere","Nikunj Simariya",""
"Ryan Soul","Individual","","","",""
"S.H.I.E.L.D. Trust","Sole Trader","86 138 059 408","Manish Sheladia","",""
"Sachin ","Company","","","",""
"Sachin BH","Sole Trader","","","",""
"Sapphire ","Other","","","",""
"sheladia company","Company","","Manish Sheladia","",""
"Silicon Valley","Sole Trader","","","",""
"Silver Soul Pty Ltd","Company","","","",""
"Simiriya group","Partnership","","Nikunj 1","",""
"SkyTech","Individual","","","",""
"Smit Pty Ltd","Company","66 603 284 886","Manish Sheladia","Manish Sheladiya",""
"Smith and Smith","Partnership","68 697 054 433","Manish Sheladia","","AB SMITH GROUP"
"smith club","Unit Trust","","","Manish Sheladiya",""
"Smith Family Trust","Trust","42 692 268 960","Manish Sheladia","","AB SMITH GROUP"
"Smith Pty Ltd","Company","","Manish Sheladia","Manish Sheladiya",""
"Smithwell Trust","Trust","","prashant shah","",""
"Solar ","Sole Trader","","","",""
"Sole DM","Sole Trader","","","",""
"Sole Soul Holding Pty Ltd","Company","","","",""
"Sophie Thomson","Individual","","","Manish Sheladiya","Multi Services Group"
"Soul Holding Investment Trust","Trust","","","",""
"Soul Partners","Partnership","","","",""
"Stan Lee","Individual","","Manish Sheladia","",""
"Stark Enterprise Pty Ltd","Company","63 604 130 805","Manish Sheladia","Manish Sheladiya",""
"Steven Andrew","Individual","","","Nikunj Simariya","Nation Super"
"StoneHaven Inc.","Company","","Manish Sheladia","",""
"Sunrise Bakery","Company","","","",""
"Sydney Company","Company","","Nikunj 1","",""
"Tax Sorted Solution Business Trust","Trust","","","",""
"Test New Check ","Company","","Divy M","",""
"Test SMSF Jinal","Company","","","",""
"Thakorji Pty Ltd","Company","","Sachin Bhatnagar","",""
"The Trustee for Campbell Family Trust","Self Managed Superannuation Fund","25 955 919 477","Manish Sheladia","Manish Sheladiya","Amazing Group"
"Thunder fitness","Company","","","",""
"Tokyo ","Individual","","","",""
"Tony Soul","Individual","","","",""
"trust DM","Estate","","Jignesh +1","",""
"Umbrella Corporation","Sole Trader","","prashant shah","",""
"Venture Capital Pty Ltd","Company","87 113 746 884","Nikunj Simariya","Manish Sheladiya",""
"Venture Super Fund","Self Managed Superannuation Fund","12 341 254 358","Jocelyn Vere","Manish Sheladiya",""
"Venture Trust","Trust","","","",""
"Vishal ","Individual","49 819 924 176","","",""
"Warrawong Bakehouse Pty Ltd","Company","","","",""
"WB Pty Ltd","Company","38 562 565 980","","",""
"West Coast ","","","","",""
"White Flower Partners","Partnership","34 131 170 292","","Manish Sheladiya","Multi Services Group"
"Xero LTD","Sole Trader","","Nikunj 1","",""
"Yash Thomson","Individual","","","Manish Sheladiya","Multi Services Group"
"Zackstone ","Company","","","",""
"Zalliterate tester","Company","","","",""
"ZBS Pty Ltd","Company","","","",""
"ZCK Technologies","Partnership","86 880 684 769","Manish Sheladia","",""
"ZDK Pvt.Ltd","CL Business ","86 880 684 769","","",""
"Zen Anytime Fitness - Warrawong","Self Managed Superannuation Fund","27 655 744 335","Manish Sheladia","Manish Sheladiya",""
"Zid Andy Smith","Individual","","Divy M","Nikunj Simariya",""
"Zid Canadian Trader","Individual","","Nikunj Simariya","",""
"Zinc Pvt Ltd","Company","","Manish Sheladia","",""
"Zoffis Not For Profit","Not for Profit","","","",""
"zzBussiness ","Individual","","Manish Sheladia","",""
"zzloudoffis ","Company","32 895 633 132","","",""`


export const csvData_20250319223508 = `"[Client] Client","[Client] First Name","[Client] Last Name","[Client] Business Number","[Client] Business Structure","[Client] Address","[Client] Tax Agent","[Client] Account Manager"
"Aaron wings","","","","Not for Profit","","",""
"ABS Pvt.Ltd","","","","Individual","45 Steel St ","Prashant Shah","Divy Divy Divy ModiModiModiModi"
"Acer","","","85 655 468 876","Company","","",""
"Acer Champions","","","85 655 468 876","Company","","Prashant Shah","Prashant  Shah"
"alex","","","85 655 468 876","Company","","",""
"Alex","","","85 655 468 876","Company","","",""
"Alex","","","85 655 468 876","Estate","","",""
"Alex Taubman","","","37 282 969 452","Sole Trader","641-913 Steele Rd ","Prashant Shah","Parakramsinh Parmar"
"Alica ","","","","Unit Trust","795 Strettle Rd ","","Divy Divy Divy ModiModiModiModi"
"American Trust","","","","Individual","","","Divy Divy Divy ModiModiModiModi"
"American Trust Edited New","","","","Individual","","",""
"Aron HT.","","","58 702 582 891","Company","45 Screen St ","","Parakramsinh Parmar"
"Ascend Financial","","","","Company","","",""
"Ashley W. ","","","","private funds","","",""
"Awesome Accounting ","","","","Company","","",""
"Bethany Hassell","","","","Company","","",""
"Bhumit Test","","","","Company","","",""
"Bruce Lee ","","","70 124 588 561","Individual","sfff","Prashant Shah","Divy Divy Divy ModiModiModiModi"
"Bruce Wayne Pty Ltd","","","","Sole Trader","96 Coleraine Rd ","Prashant Shah","Parakramsinh Parmar"
"Carol R. Morgan","","","66 712 931 973","Company","19 Steetley Lane E ","","Prashant  Shah"
"Catalyst Financial Solutions","","","","Company","","",""
"Charli Reilly","","","","Company","","Prashant Shah","Divy Divy Divy ModiModiModiModi"
"Clarity Accounting & Consulting","","","","Company","","",""
"Cloudoffis Club","","","","Company","","","Divy Divy Divy ModiModiModiModi"
"Co $ Co company","","","","Partnership","","",""
"Daniel Prenzel","","","","Individual","","",""
"David $ David","","","","","","",""
"Divy Modi ","","","","Individual","","Prashant Shah",""
"Eliza ","","","61 779 388 676","Individual","159 Rode Rd ","Prashant Shah","Divy Divy Divy ModiModiModiModi"
"Emily Eales","","","","Public funds","","",""
"Emily Garrard","","","","Company","","",""
"Endorson pvt ltd","","","","Sole Trader","","","Parakramsinh Parmar"
"Eric A","","","","Company","","",""
"Eve Phillip","","","99 495 452 829","entertainment companies","236-256 Melbourne St ","Prashant Shah","Divy Divy Divy ModiModiModiModi"
"Evie Joseph 1","","","58 702 582 891","entertainment companies","56 High Street Rd ","Prashant Shah","Divy Divy Divy ModiModiModiModi"
"Evolve Accounting","","","","Company","","",""
"Flynn Gell","","","","Other","","",""
"Foresight Accounting","","","","Company","","",""
"Harrison Lawes","","","","CE Custom tech ","52 Cadell Rd ","","Divy Divy Divy ModiModiModiModi"
"Jai Cairns","","","","Holding ","","",""
"Jake Hays","","","","Company","","","Divy Divy Divy ModiModiModiModi"
"James L. Johnson","","","","Jignesh","","",""
"Jasmine Handfield","test 1","test 2","","Holding Company of trust Australia zone Holding Company of trust Australia zone Holding Company of","139-169 Potassium St ","",""
"Jeremy Derrington","","","","Club or Society","","",""
"Jesse ","","","","private funds","","",""
"Jet Pvt Ltd","","","","Company","132 Stewarts Rd ","",""
"Jett Longmore","","","23 614 069 859","Company","133 Streeton Dr ","",""
"Jhonson Family Trust","","","85 655 468 876","Sole Trader","27 Georgette St ","Prashant Shah","Divy Divy Divy ModiModiModiModi"
"John Snow Pty Ltd","","","","Partnership","192 Sterling Dr ","","Prashant  Shah"
"Jones.","","","73 516 095 794","Company","126 Oxley Station Rd ","Prashant Shah","Prashant  Shah"
"Justin Dorsch","","","58 702 582 891","CE Custom tech ","2 Cole Ct ","",""
"Kate ","","","27 655 744 335","Company","54 Copernicus Rd ","Prashant Shah","Divy Divy Divy ModiModiModiModi"
"Katie ","","","","CE Custom tech ","23 Cade Way ","",""
"Kayla Dadswell","","","","Superannuation Fund","","",""
"Krupa ","","","","Krupa Test ","","",""
"M. Mathews","","","","entertainment companies","","",""
"Marvel","","","","Company","Las Vegas ","",""
"McCraw","Test ","Modi","","Individual","","","Prashant  Shah"
"Michael J. Glassman","","","","Tax Sorted Demo","","",""
"Milla Heath","","","","Company","58 Coleman Rd ","Prashant Shah","Parakramsinh Parmar"
"MiracleGroup","","","","Company","","","Divy Divy Divy ModiModiModiModi"
"Mitchell Bryant","","","","Sole Trader","","",""
"Modi ","","","","Modi","","",""
"Modi & Partners ","","","","Partnership","12 Madora Beach Rd ","",""
"Momentum Accounting","","","","Company","","",""
"NavPoint Financial","","","","Company","","",""
"Oliver grey","","","","CE Custom tech ","","Prashant Shah","Prashant  Shah"
"Olivia Dooley","","","27 655 744 335","Company","96 Coogee Bay Rd ","","Parakramsinh Parmar"
"Patrick Entertain company","","","","entertainment companies","","",""
"Percy S. Honaker","","","","Company","","",""
"PS","","","","private funds","","","Divy Divy Divy ModiModiModiModi"
"PS Technologies Pty LTD","","","90 600 590 038","Partnership","17 Streeters Rd ","Prashant Shah",""
"Pualo Alto ","","","","Unit Trust","","","Divy Divy Divy ModiModiModiModi"
"Quantum Financial","","","","Partnership","","",""
"Rebecca Hook","","","","Company","","",""
"Rebecca Swayne","","","82 366 993 541","Government Entity","Mount 123 Paramatta","Prashant Shah","Parakramsinh Parmar"
"Richard B. Rivers","","","","July Test","45 Carawa Rd ","",""
"S. Holland","","","","CE Custom tech ","Atladara ","",""
"Sachin Pty Ltd","","","","Company","","",""
"Sam charis","","","","Other","","","Prashant  Shah"
"Seth Hort","","","","private funds","","",""
"Sharon J","","","","Trust","","",""
"Sofia Oakley","","","65 193 169 138","Sole Trader","sfff","Prashant Shah","Prashant  Shah"
"Softech info.","","","","Holding Company of Trust","","",""
"STARK ADVISORY PTY LTD","","","","Company","Level 3 15 Bourke Rd ","Prashant Shah","Prashant  Shah"
"stark solution","","","","Tax Sorted Demo","","",""
"Streamline Financial","","","","Sole Trader","","",""
"Susan C. Brett","","","","Company","","",""
"Sydney Strikers LLP","","","","Company","","",""
"Thomas co.","","","","CE Custom tech ","","",""
"Tony Traders ","","","","Company","23 Steere Cres ","",""
"Tyler Annand","","","","Self Managed Superannuation Fund","","",""
"Tyler B. ","","","","Self Managed Superannuation Fund","","",""
"Unit Company ","","","","Trust","","","Divy Divy Divy ModiModiModiModi"
"Veracity Financial","","","","Company","","",""
"Wayne Enterprises Pvt.Ltd","","","","Individual","89 Streeton Dr ","","Prashant  Shah"
"XYZ Pty Ltd test","","","","CE Custom tech ","Test new ","",""`


// -------------------

export const csvData = `[Client] Client,[Client] Business Structure,[Client] Business Number,[Client] Account Manager,[Client] Tax Agent,[Client] Group(s)
ABRAHAM LLP,Partnership,65 101 795 397,Nikunj Simariya,,
Abraham Venture Trust,Trust,64 101 586 230,Dilnar Tangri,Manish Sheladiya,
Amazing Family Trust,Trust,84 118 155 258,,Nikunj Simariya,Nation Super
Amazing Grace accupuncture clinic,Sole Trader,75 725 627 667,Divy M,,
Amazing Pet Care Pty Ltd,Company,49 898 197 911,Manish Sheladia,Manish Sheladiya,Amazing Group
Andy Smith Remove,,,,Manish Sheladiya,AB SMITH GROUP
ARNAUD ABRAHAM ,Individual,19 114 194 310,Sachin Bhatnagar,Nikunj Simariya,
Atlas Corp. Pty Ltd,Company,11 688 022 083,,, 
Aussie Trading Trust,Trust,37 849 875 881,Manish Sheladia,,
Balmoral Pastoral Concepts Pty Ltd,Company,13 447 453 166,Jocelyn Vere,Nikunj Simariya,Nation Super
BDP Group Ltd,Company,13 860 671 162,,, 
Billion $ Unicorn Pty Ltd,Company,47 661 378 838,Manish Sheladia,Manish Sheladiya,
Bluebird Beverages Pty Ltd,Company,78 004 551 473,,,
Bondi Consulting Partners,Partnership,29 580 551 984,Manish Sheladia,,
Bray Family Superannuation Fund,Self Managed Superannuation Fund,63 059 981 823,Manish Sheladia,,`;
